[package]
name = "nexo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
once_cell = "1.21.3"
dashmap = "6.1.0"
dotenv = "0.15"

[profile.release]
debug = true