[package]
name = "nexo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = { version = "1", features = ["serde"] }
once_cell = "1.21.3"
dashmap = "6.1.0"
dotenv = "0.15"
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
parking_lot = "0.12"
chrono = "0.4"
serde_json = "1.0"

[profile.release]
debug = true